### GET Movies
GET http://localhost:8090/movie-info/list

### POST movies
POST http://localhost:8090/movie-info/save
Content-Type:application/json

[
  {
    "name": "Interstellar",
    "description": "When Earth becomes uninhabitable, a team of ex-NASA pilots travels through a wormhole to find a new home for humanity.",
    "path": "https://www.youtube.com/watch?v=zSWdZVtXT7E"
  },
  {
    "name": "Spiderman: Into the Spider-Verse",
    "description": "Teen Miles Morales becomes the new Spider-Man and joins five spider-powered individuals from other dimensions to stop a threat.",
    "path": "https://www.youtube.com/watch?v=g4Hbz2jLxvQ"
  },
  {
    "name": "The Dark Knight",
    "description": "When the menace known as the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological and physical tests.",
    "path": "https://www.youtube.com/watch?v=EXeTwQWrcwY"
  },
  {
    "name": "Inception",
    "description": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea.",
    "path": "https://www.youtube.com/watch?v=YoHD9XEInc0"
  },
  {
    "name": "Spirited Away",
    "description": "A young girl wanders into a world ruled by gods, witches, and spirits, where humans are changed into beasts.",
    "path": "https://www.youtube.com/watch?v=ByXuk9QqQkk"
  }
]
### Get Movie Stream
GET http://localhost:8091/stream/redirect/3